# -*- coding: utf-8 -*-
"""generative_fine_tuning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12T6agq99L5gSohfiTlkECJdC00kxWUSO
"""

!pip install pandas transformers

import pandas as pd
import json

data = [

{"prompt":"What is the return policy of the company?",
"completion":"The company offers a 30-day return policy for all products. Items must be in original condition with tags attached."},

{"prompt":"How can customers start a return request?",
"completion":"Customers can start a return request by contacting the support team through email."},

{"prompt":"How can a customer initiate a return?",
"completion":"Customers can initiate a return by contacting the support team at support@company.com."},

{"prompt":"Is there a time limit for returning products?",
"completion":"Yes, products can be returned within 30 days if they are in their original condition."},

{"prompt":"What condition must items be in for returns?",
"completion":"Items must be unused and in their original condition with tags attached."},

{"prompt":"How long does standard shipping take?",
"completion":"Standard shipping usually takes 5-7 business days."},

{"prompt":"How long does express shipping take?",
"completion":"Express shipping typically takes 2-3 business days."},

{"prompt":"What is the estimated delivery time for international orders?",
"completion":"International shipping may take between 10 and 15 business days depending on the destination."},

{"prompt":"Does the company provide customer support?",
"completion":"Yes, the company provides 24/7 customer support to assist customers."},

{"prompt":"How can customers contact support?",
"completion":"Customers can contact support via email or phone."},

{"prompt":"What are the customer support contact options?",
"completion":"Support can be reached by email at support@company.com or by phone at 1-800-COMPANY."},

{"prompt":"Is customer service available all day?",
"completion":"Yes, customer support is available 24 hours a day, 7 days a week."},

{"prompt":"When is live chat support available?",
"completion":"Live chat support is available Monday to Friday from 9 AM to 6 PM EST."},

{"prompt":"What payment methods are accepted?",
"completion":"The company accepts Visa, MasterCard, American Express, PayPal, and bank transfers."},

{"prompt":"Can customers pay using PayPal?",
"completion":"Yes, PayPal is one of the accepted payment methods."},

{"prompt":"Are credit cards accepted for payment?",
"completion":"Yes, Visa, MasterCard, and American Express credit cards are accepted."},

{"prompt":"Are payments secure?",
"completion":"Yes, all payments are processed using secure SSL encryption."},

{"prompt":"What security technology is used for transactions?",
"completion":"The company secures all transactions using SSL encryption technology."},

{"prompt":"How can customers track their orders?",
"completion":"Customers receive an email with a tracking number after their order is shipped."},

{"prompt":"Where can customers track their orders?",
"completion":"Orders can be tracked through the 'My Orders' section on the website or on the carrier's website."},

{"prompt":"Do customers receive tracking information after shipping?",
"completion":"Yes, a tracking email is sent once the order has been shipped."},

{"prompt":"When was TechCorp Solutions founded?",
"completion":"TechCorp Solutions was founded in 2015."},

{"prompt":"In which year was TechCorp established?",
"completion":"TechCorp Solutions was established in 2015."},

{"prompt":"What is the mission of TechCorp Solutions?",
"completion":"The mission of TechCorp Solutions is to deliver innovative software solutions for small and medium businesses."},

{"prompt":"What type of companies does TechCorp focus on?",
"completion":"TechCorp focuses on providing solutions for small and medium-sized businesses."},

{"prompt":"What products does TechCorp offer?",
"completion":"TechCorp offers CloudSync, SecureVault, and Analytics Pro."},

{"prompt":"What is CloudSync?",
"completion":"CloudSync is a product designed for file management."},

{"prompt":"What is CloudSync used for?",
"completion":"CloudSync helps users manage and store files efficiently."},

{"prompt":"What is SecureVault?",
"completion":"SecureVault is a solution designed for data protection and security."},

{"prompt":"What does SecureVault help with?",
"completion":"SecureVault helps businesses secure their data."},

{"prompt":"What is Analytics Pro?",
"completion":"Analytics Pro is a tool designed for business intelligence and data analysis."},

{"prompt":"What does Analytics Pro do?",
"completion":"Analytics Pro helps companies analyze business data and gain insights."},

{"prompt":"What is the price of the Basic plan?",
"completion":"The Basic plan starts at $29 per month."},

{"prompt":"How much does the Basic plan cost?",
"completion":"The Basic plan costs $29 per month."},

{"prompt":"What is the price of the Professional plan?",
"completion":"The Professional plan costs $79 per month."},

{"prompt":"How much does the Professional plan cost?",
"completion":"The Professional plan is priced at $79 per month."},

{"prompt":"What is the price of the Enterprise plan?",
"completion":"The Enterprise plan costs $199 per month."},

{"prompt":"What is included in the Enterprise plan?",
"completion":"The Enterprise plan includes advanced features along with full support."},

{"prompt":"Do all pricing plans include support?",
"completion":"Yes, all pricing plans include free setup and 24/7 customer support."},

{"prompt":"Is support included in every plan?",
"completion":"Yes, every plan includes full support and setup assistance."},

{"prompt":"How can someone contact TechCorp?",
"completion":"Customers can contact TechCorp via email at info@techcorp.com or by phone."},

{"prompt":"What is the email address for TechCorp?",
"completion":"The contact email for TechCorp is info@techcorp.com."},

{"prompt":"What phone number can customers use to contact TechCorp?",
"completion":"Customers can call +1-555-TECHCORP."},

{"prompt":"Where is TechCorp located?",
"completion":"TechCorp is located at 123 Tech Street, San Francisco, CA 94105."},

{"prompt":"What is the address of TechCorp?",
"completion":"TechCorp's office is located at 123 Tech Street, San Francisco, CA 94105."},

{"prompt":"Which city is TechCorp based in?",
"completion":"TechCorp is based in San Francisco, California."},

{"prompt":"Does TechCorp offer software solutions?",
"completion":"Yes, TechCorp offers software solutions such as CloudSync, SecureVault, and Analytics Pro."},

{"prompt":"What type of services does TechCorp provide?",
"completion":"TechCorp provides software tools for file management, data security, and business analytics."},

{"prompt":"Who are the main users of TechCorp products?",
"completion":"TechCorp products are mainly used by small and medium-sized businesses."},

{"prompt":"Does TechCorp provide business analytics tools?",
"completion":"Yes, TechCorp provides business analytics tools through its product Analytics Pro."}

]

df = pd.DataFrame(data)

df.to_csv("dataset/techcorp.csv", index=False)


def save_jsonl(df, filename):

    with open(filename, "w") as f:

        for _, row in df.iterrows():

            entry = {

                "text": f"""
### Instruction:
{row['prompt']}

### Response:
{row['completion']}
"""
            }

            f.write(json.dumps(entry) + "\n")


train_df = df.sample(frac=0.8, random_state=42)
test_df = df.drop(train_df.index)

save_jsonl(train_df, "dataset/train.jsonl")
save_jsonl(test_df, "dataset/test.jsonl")

print("Dataset created")

import os
os.makedirs("dataset", exist_ok=True)

from transformers import AutoTokenizer, AutoModelForCausalLM
from datasets import load_dataset
from transformers import TrainingArguments, Trainer
import torch

# Model 
model_name = "TinyLlama/TinyLlama-1.1B-Chat-v1.0"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name)
tokenizer.pad_token = tokenizer.eos_token

# Load model
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto"
)

# Enable gradient checkpointing (reduces memory)
model.gradient_checkpointing_enable()

# Load dataset
dataset = load_dataset(
    "json",
    data_files={
        "train": "/content/dataset/train.jsonl",
        "test": "/content/dataset/test.jsonl"
    }
)

# Tokenization
def tokenize(example):

    tokenized = tokenizer(
        example["text"],
        truncation=True,
        padding="max_length",
        max_length=256   
    )

    tokenized["labels"] = tokenized["input_ids"].copy()

    return tokenized


tokenized_dataset = dataset.map(tokenize, remove_columns=["text"])


# Training parameters
training_args = TrainingArguments(
    output_dir="./techcorp-model",
    num_train_epochs=3,
    per_device_train_batch_size=1,   
    gradient_accumulation_steps=4,   
    logging_steps=5,
    save_steps=50,
    learning_rate=2e-5,
    save_total_limit=2
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_dataset["train"]
)

# Clear GPU memory
torch.cuda.empty_cache()

# Train
trainer.train()

# Save model
trainer.save_model("techcorp-finetuned-model")
tokenizer.save_pretrained("techcorp-finetuned-model")



from transformers import pipeline

pipe = pipeline(
"text-generation",
model="/content/techcorp-finetuned-model"
)

prompt = """
### Instruction:
Which city is TechCorp based in?

### Response:
"""

result = pipe(prompt, max_length=200)

print(result[0]["generated_text"])

